apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: cmr-granule-locator
spec:
  templates:
    - name: cmr-granule-locator
      inputs:
        parameters:
          - name: operation
          - name: query
          - name: page-size
          - name: image
          - name: batch-size
          - name: image-pull-policy
          - name: timeout
          - name: CMR_ENDPOINT
      outputs:
        parameters:
          - name: batch-catalogs
            valueFrom:
              path: /tmp/batch-catalogs.json
      podSpecPatch: '{"activeDeadlineSeconds":{{inputs.parameters.timeout}}}'
      container:
        image: "{{inputs.parameters.image}}"
        imagePullPolicy: "{{inputs.parameters.image-pull-policy}}"
        args:
          [
            "--harmony-input",
            "{{inputs.parameters.operation}}",
            '--query',
            "{{inputs.parameters.query}}",
            '--output-dir',
            '/tmp/outputs',
            '--page-size',
            "{{inputs.parameters.page-size}}",
            "--harmony-input",
            "{{inputs.parameters.operation}}",
          ]
        env:
          - name: CMR_ENDPOINT
            value: "{{inputs.parameters.CMR_ENDPOINT}}"
          - name: SHARED_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: shared-secret
                key: secret-key
