apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: exit-handler
spec:
  templates:
    - name: exit-handler
      inputs:
        parameters:
          - name: image-pull-policy
          - name: timeout
          - name: callback
          - name: status
          - name: failures
      podSpecPatch: '{"activeDeadlineSeconds":{{inputs.parameters.timeout}}}'
      script:
        image: "everpeace/curl-jq"
        imagePullPolicy: "{{inputs.parameters.image-pull-policy}}"
        command: [sh]
        source: |
<SOURCE>