apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: exit-handler
spec:
  templates:
    - name: exit-handler
      inputs:
        parameters:
          - name: image-pull-policy
          - name: timeout
          - name: callback
          - name: status
          - name: failures
      podSpecPatch: '{"activeDeadlineSeconds":{{inputs.parameters.timeout}}}'
      script:
        image: "everpeace/curl-jq"
        imagePullPolicy: "{{inputs.parameters.image-pull-policy}}"
        command: [sh]
        source: |
          # timing
          timestamp=`date +%Y-%m-%dT%H:%M:%S.%3NZ`
          echo "{\"level\": \"info\", \"timestamp\": \"$timestamp\", \"message\": \"timing.exit-handler.start\"}"
          start_time_millis=`date +%s%3N`
          echo '{{inputs.parameters.failures}}' > /tmp/failures
          error="{{inputs.parameters.status}}"
          timeout_count=$(grep -c 'Pod was active on the node longer than the specified deadline' /tmp/failures)
          if [ "$timeout_count" != "0" ]
          then
          error="Request%20timed%20out"
          fi
          if [ "{{inputs.parameters.status}}" = 'Succeeded' ]
          then
          curl -XPOST "{{inputs.parameters.callback}}/response?status=successful&argo=true" > /dev/null
          else
          curl -XPOST "{{inputs.parameters.callback}}/response?status=failed&argo=true&error=$error" > /dev/null
          fi
          end_time_millis=`date +%s%3N`
          duration_ms=$(($end_time_millis-$start_time_millis))
          timestamp=`date +%Y-%m-%dT%H:%M:%S.%3NZ`
          echo "{\"level\": \"info\", \"timestamp\": \"$timestamp\", \"durationMs\": $duration_ms, \"message\": \"timing.exit-handler.end\"}"

          