apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: query-cmr
spec:
  templates:
    - name: query-cmr
      inputs:
        parameters:
          - name: operation
          - name: query
          - name: page-size
          - name: batch-size
          - name: image-pull-policy
          - name: timeout
      outputs:
        artifacts:
          - name: metadata
            path: /tmp/outputs
        parameters:
          - name: batch-count
            valueFrom:
              path: /tmp/outputs/batch-count.txt
          - name: batch-catalogs
            valueFrom:
              path: /tmp/outputs/batch-catalogs.json
      podSpecPatch: '{"activeDeadlineSeconds":{{inputs.parameters.timeout}}}'
      container:
        image: "<DOCKER_IMAGE>"
        imagePullPolicy: "{{inputs.parameters.image-pull-policy}}"
        args:
          [
            "--harmony-input",
            "{{inputs.parameters.operation}}",
            "--query",
            "{{inputs.parameters.query}}",
            "--output-dir",
            "/tmp/outputs",
            "--batch-size",
            "{{inputs.parameters.batch-size}}",
            "--page-size",
            "{{inputs.parameters.page-size}}",
          ]
        envFrom:
          - configMapRef:
              name: harmony-env
          - secretRef:
              name: harmony-secrets
