apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: result-handler
spec:
  templates:
    - name: result-handler
      inputs:
        artifacts:
          - name: metadata
            path: /tmp/metadata
        parameters:
          - name: stac-catalog-link
          - name: image-pull-policy
          - name: timeout
          - name: callback
          - name: batch-count
          - name: should-post-results
          - name: post-batch-step-count
      podSpecPatch: '{"activeDeadlineSeconds":{{inputs.parameters.timeout}}}'
      script:
        image: "everpeace/curl-jq"
        imagePullPolicy: "{{inputs.parameters.image-pull-policy}}"
        command: [bash]
        envFrom:
          - configMapRef:
              name: harmony-env
        env:
          - name: SHOULD_POST_RESULTS
            value: "{{inputs.parameters.should-post-results}}"
        source: |
<SOURCE>