plugins:
  - import
  - jsdoc
  - node
extends:
  - airbnb-base
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:node/recommended
env:
  jasmine: true
  mocha: true
  node: true
rules:
  indent: ["error", 2]
  no-restricted-syntax: ["error", "LabeledStatement", "WithStatement"]
  require-jsdoc:
    - warn
  valid-jsdoc:
    - warn