version: '3.6'

services:
  localstack:
    container_name: localstack
    image: localstack/localstack:0.11.1
    ports:
      - "4566:4566"
      - "4572:4572"
      - "4592:4592"
      - "8080:8080"
    environment:
      LOCALSTACK_SERVICES: s3,sts
      LOCALSTACK_DEBUG: 1
    volumes:
      - ./tmp/localstack:/docker-entrypoint-initaws.d
