version: '3.6'

x-service: &default-service
  restart: unless-stopped
  depends_on:
    - localstack
  environment: &default-environment
    USE_LOCALSTACK: ${USE_LOCALSTACK}
    LOCALSTACK_HOST: localstack
    AWS_DEFAULT_REGION: us-west-2
    EDL_USERNAME: ${EDL_USERNAME}
    EDL_PASSWORD: ${EDL_PASSWORD}
    STAGING_BUCKET: ${STAGING_BUCKET}
    TEXT_LOGGER: ${TEXT_LOGGER}

services:
  harmony-gdal:
    <<: *default-service
    container_name: harmony-gdal
    image: harmony/gdal
    command: --harmony-action start --harmony-queue-url http://localstack:4566/queue/harmony-gdal-queue
    environment:
      <<: *default-environment
      STAGING_PATH: public/harmony/gdal
      APP_NAME: harmony-gdal
      PYTHONPATH: /usr/lib/harmony-service-lib-py
    volumes:
      - ../harmony-gdal:/home
      - ../harmony-service-lib-py/harmony:/usr/lib/harmony-service-lib-py/harmony

  sds-swot-reproject:
    <<: *default-service
    container_name: sds-swot-reproject
    image: sds/swot-reproject
    command: --harmony-action start --harmony-queue-url http://localstack:4566/queue/sds-swot-reproject-queue
    environment:
      <<: *default-environment
      STAGING_PATH: public/sds/swot-reproject
      APP_NAME: sds-swot-reproject

  sds-variable-subsetter:
    <<: *default-service
    container_name: sds-variable-subsetter
    image: sds/variable-subsetter
    command: --harmony-action start --harmony-queue-url http://localstack:4566/queue/sds-variable-subsetter-queue
    environment:
      <<: *default-environment
      STAGING_PATH: public/sds/variable-subsetter
      APP_NAME: sds-variable-subsetter

  harmony-netcdf-to-zarr:
    <<: *default-service
    container_name: harmony-netcdf-to-zarr
    image: harmony/netcdf-to-zarr
    command: --harmony-action start --harmony-queue-url http://localstack:4566/queue/harmony-netcdf-to-zarr-queue
    environment:
      <<: *default-environment
      STAGING_PATH: public/harmony/netcdf-to-zarr
      APP_NAME: harmony-netcdf-to-zarr
      PYTHONPATH: /usr/lib/harmony-service-lib-py
    volumes:
      - ../harmony-netcdf-to-zarr:/home
      - ../harmony-service-lib-py/harmony:/usr/lib/harmony-service-lib-py/harmony

  localstack:
    container_name: localstack
    image: localstack/localstack:0.11.1
    ports:
      - "4566:4566"
      - "4572:4572"
      - "4576:4576"
      - "4592:4592"
      - "8080:8080"
    environment:
      LOCALSTACK_SERVICES: s3,sts,sqs
      LOCALSTACK_DEBUG: 1
    volumes:
      - ./tmp/localstack:/docker-entrypoint-initaws.d
