version: '3.6'

x-service: &default-service
  restart: unless-stopped
  depends_on:
    - localstack
  environment: &default-environment
    USE_LOCALSTACK: ${USE_LOCALSTACK}
    LOCALSTACK_HOST: localstack
    AWS_DEFAULT_REGION: us-west-2
    EDL_USERNAME: ${EDL_USERNAME}
    EDL_PASSWORD: ${EDL_PASSWORD}
    STAGING_BUCKET: ${STAGING_BUCKET}
    TEXT_LOGGER: ${TEXT_LOGGER}

services:
  localstack:
    container_name: localstack
    image: localstack/localstack:0.11.1
    ports:
      - "4566:4566"
      - "4572:4572"
      - "4576:4576"
      - "4592:4592"
      - "8080:8080"
    environment:
      LOCALSTACK_SERVICES: s3,sts,sqs
      LOCALSTACK_DEBUG: 1
    volumes:
      - ./tmp/localstack:/docker-entrypoint-initaws.d
