apiVersion: apps/v1
kind: Deployment
metadata:
  name: netcdf-to-zarr
  labels:
    name: netcdf-to-zarr
spec:
  replicas: 1
  selector:
    matchLabels:
      name: netcdf-to-zarr
  template:
    metadata:
      labels:
        name: netcdf-to-zarr
    spec:
      containers:
        - name: worker
          imagePullPolicy: $HARMONY_NETCDF_TO_ZARR_IMAGE_PULL_POLICY
          image: $HARMONY_NETCDF_TO_ZARR_IMAGE
          resources:
            limits:
              memory: $HARMONY_NETCDF_TO_ZARR_LIMITS_MEMORY
            requests:
              memory: $HARMONY_NETCDF_TO_ZARR_REQUESTS_MEMORY
          envFrom:
          - configMapRef:
              name: harmony-env
          - secretRef:
              name: harmony-secrets
          env:
            - name: TEXT_LOGGER
              value: "false"
          volumeMounts:
            - mountPath: /tmp/metadata
              name: test-volume
          command: ["/bin/sh", "-c"]
          args:
            - while true; do
                date;
                sleep 10;
              done
        - name: manager
          imagePullPolicy: IfNotPresent
          image: $SERVICE_RUNNER_IMAGE
          resources:
            limits:
              memory: $SERVICE_RUNNER_LIMITS_MEMORY
            requests:
              memory: $SERVICE_RUNNER_REQUESTS_MEMORY
          envFrom:
          - configMapRef:
              name: harmony-env
          - secretRef:
              name: harmony-secrets
          env:
          - name: BACKEND_HOST
            value: $BACKEND_HOST
          - name: BACKEND_PORT
            value: "$BACKEND_PORT"
          - name: HARMONY_SERVICE
            value: $HARMONY_NETCDF_TO_ZARR_IMAGE
          - name: WORKING_DIR
            value: "/opt/harmony-netcdf-to-zarr"
          - name: INVOCATION_ARGS
            value: |-
              python
              -m
              harmony_netcdf_to_zarr
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          ports:
            - containerPort: 5000
          volumeMounts:
            - mountPath: /tmp/metadata
              name: test-volume
      volumes:
      - name: test-volume
        hostPath:
          # directory location on host
          path: $HOST_VOLUME_PATH
          # this field is optional
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: netcdf-to-zarr
spec:
  ports:
    - name: frontend
      port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    name: netcdf-to-zarr
  type: LoadBalancer