apiVersion: apps/v1
kind: Deployment
metadata:
  name: podaac-l2-subsetter
  labels:
    name: podaac-l2-subsetter
spec:
  replicas: 1
  selector:
    matchLabels:
      name: podaac-l2-subsetter
  template:
    metadata:
      labels:
        name: podaac-l2-subsetter
    spec:
      terminationGracePeriodSeconds: $DEFAULT_ARGO_POD_TIMEOUT_SECS
      containers:
        - name: worker
          imagePullPolicy: $PODAAC_L2_SUBSETTER_IMAGE_PULL_POLICY
          image: $PODAAC_L2_SUBSETTER_IMAGE
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh","-c","touch /tmp/lock/TERMINATING; while [ -f /tmp/lock/WORKING ]; do sleep 1; done; kill -TERM 1"]
          resources:
            limits:
              memory: $PODAAC_L2_SUBSETTER_LIMITS_MEMORY
            requests:
              memory: $PODAAC_L2_SUBSETTER_REQUESTS_MEMORY
          envFrom:
          - configMapRef:
              name: harmony-env
          - secretRef:
              name: harmony-secrets
          env:
            - name: TEXT_LOGGER
              value: "false"
          volumeMounts:
            - mountPath: /tmp/metadata
              name: test-volume
            - mountPath: /tmp/lock
              name: ephemeral-volume
          command: ["/bin/sh", "-c"]
          args:
            - trap "exit 0" TERM;
              while true; do
                date;
                sleep 10;
              done
        - name: manager
          imagePullPolicy: IfNotPresent
          image: $SERVICE_RUNNER_IMAGE
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh","-c","touch /tmp/lock/TERMINATING; while [ -f /tmp/lock/WORKING ]; do sleep 1; done; kill -TERM 1"]
          resources:
            limits:
              memory: $SERVICE_RUNNER_LIMITS_MEMORY
            requests:
              memory: $SERVICE_RUNNER_REQUESTS_MEMORY
          envFrom:
          - configMapRef:
              name: harmony-env
          - secretRef:
              name: harmony-secrets
          env:
          - name: BACKEND_HOST
            value: $BACKEND_HOST
          - name: BACKEND_PORT
            value: "$BACKEND_PORT"
          - name: HARMONY_SERVICE
            value: $PODAAC_L2_SUBSETTER_IMAGE
          - name: INVOCATION_ARGS
            value: |-
              ./docker-entrypoint.sh
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          ports:
            - containerPort: 5000
          volumeMounts:
            - mountPath: /tmp/metadata
              name: test-volume
            - mountPath: /tmp/lock
              name: ephemeral-volume
      volumes:
      - name: test-volume
        hostPath:
          # directory location on host
          path: $HOST_VOLUME_PATH
          # this field is optional
          type: DirectoryOrCreate
      - name: ephemeral-volume
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: podaac-l2-subsetter
spec:
  ports:
    - name: frontend
      port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    name: podaac-l2-subsetter
  type: ClusterIP