apiVersion: apps/v1
kind: Deployment
metadata:
  name: trajectory-subsetter
  labels:
    name: trajectory-subsetter
spec:
  replicas: 1
  selector:
    matchLabels:
      name: trajectory-subsetter
  template:
    metadata:
      labels:
        name: trajectory-subsetter
      annotations:
        prometheus.io/port: "5000"
        prometheus.io/scrape: "true"
    spec:
      terminationGracePeriodSeconds: $DEFAULT_ARGO_POD_TIMEOUT_SECS
      containers:
        - name: worker
          imagePullPolicy: $TRAJECTORY_SUBSETTER_IMAGE_PULL_POLICY
          image: $TRAJECTORY_SUBSETTER_IMAGE
          resources:
            limits:
              memory: $TRAJECTORY_SUBSETTER_LIMITS_MEMORY
            requests:
              memory: $TRAJECTORY_SUBSETTER_REQUESTS_MEMORY
          envFrom:
          - configMapRef:
              name: harmony-env
          - secretRef:
              name: harmony-secrets
          env:
            - name: TEXT_LOGGER
              value: "false"
          volumeMounts:
            - mountPath: /tmp/metadata
              name: test-volume
            - mountPath: /tmp
              name: ephemeral-volume
          command: ["/bin/sh", "-c"]
          args:
            - while true; do
                date;
                sleep 10;
              done
        - name: manager
          imagePullPolicy: IfNotPresent
          image: $SERVICE_RUNNER_IMAGE
          resources:
            limits:
              memory: $SERVICE_RUNNER_LIMITS_MEMORY
            requests:
              memory: $SERVICE_RUNNER_REQUESTS_MEMORY
          envFrom:
          - configMapRef:
              name: harmony-env
          - secretRef:
              name: harmony-secrets
          env:
          - name: BACKEND_HOST
            value: $BACKEND_HOST
          - name: BACKEND_PORT
            value: "$BACKEND_PORT"
          - name: HARMONY_SERVICE
            value: $TRAJECTORY_SUBSETTER_IMAGE
          - name: WORKING_DIR
            value: "/home"
          - name: INVOCATION_ARGS
            value: |-
              python
              harmony_service/adapter.py
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          ports:
            - containerPort: 5000
          volumeMounts:
            - mountPath: /tmp/metadata
              name: test-volume
            - mountPath: /tmp
              name: ephemeral-volume
      volumes:
      - name: test-volume
        hostPath:
          # directory location on host
          path: $HOST_VOLUME_PATH
          # this field is optional
          type: DirectoryOrCreate
      - name: ephemeral-volume
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: trajectory-subsetter
spec:
  ports:
    - name: frontend
      port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    name: trajectory-subsetter
  type: ClusterIP
