reporter: mocha-multi
reporterOptions: 'spec=-,mocha-junit-reporter=-'
file: # Files that get loaded before suite execution.  Helpful when running a single file.
  - test/helpers/env.ts
extension:
  - ts
require:
  - ts-node/register
recursive: true
exit: true
timeout: 2000
