apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: asf-gdal-subsetter
spec:
  entrypoint: asf-gdal-subsetter-steps
  templates:
    - name: asf-gdal-subsetter-steps
      inputs:
        artifacts:
        - name: metadata
        parameters:
          - name: operation
          - name: stac-catalog-link
          - name: image-pull-policy
          - name: timeout
          - name: STAGING_PATH
      steps:
      - - name: last-step
          template: asf-gdal-subsetter-service
          arguments:
            artifacts:
            - name: metadata
              from: "{{inputs.artifacts.metadata}}"
            parameters:
            - name: operation
              value: "{{inputs.parameters.operation}}"
            - name: stac-catalog-link
              value: "{{inputs.parameters.stac-catalog-link}}"
            - name: image-pull-policy
              value: "{{inputs.parameters.image-pull-policy}}"
            - name: timeout
              value: "{{inputs.parameters.timeout}}"
            - name: STAGING_PATH
              value: "{{inputs.parameters.STAGING_PATH}}"
      outputs:
        artifacts:
          - name: metadata
            from: "{{steps.last-step.outputs.artifacts.metadata}}"
        parameters:
          - name: stac-catalog-link
            valueFrom:
              parameter: "{{steps.last-step.outputs.parameters.stac-catalog-link}}"
    - name: asf-gdal-subsetter-service
      inputs:
        artifacts:
        - name: metadata
          path: /tmp/metadata
        parameters:
          - name: operation
          - name: stac-catalog-link
          - name: image-pull-policy
          - name: timeout
          - name: STAGING_PATH
      outputs:
        artifacts:
        # generate metadata artifact from /tmp/outputs directory
          - name: metadata
            path: /tmp/outputs/metadata
        parameters:
          - name: stac-catalog-link
            value: catalog.json
          - name: operation
            valueFrom:
              path: /tmp/outputs/metadata/message.json
      podSpecPatch: '{"activeDeadlineSeconds":{{inputs.parameters.timeout}}}'
      container:
        image: "<DOCKER_IMAGE>"
        imagePullPolicy: "{{inputs.parameters.image-pull-policy}}"
        command: ["python3"]
        args:
          [
            "-m",
            "gdal_subsetter",
            "--harmony-action",
            "invoke",
            "--harmony-input",
            "{{inputs.parameters.operation}}",
            "--harmony-sources",
            "{{inputs.artifacts.metadata.path}}/{{inputs.parameters.stac-catalog-link}}",
            "--harmony-metadata-dir",
            "{{outputs.artifacts.metadata.path}}"
          ]
        envFrom:
          - configMapRef:
              name: harmony-env
          - secretRef:
              name: harmony-secrets
        env:
          - name: STAGING_PATH
            value: "{{inputs.parameters.STAGING_PATH}}"

