apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: harmony-netcdf-to-zarr
  namespace: argo
spec:
  entrypoint: harmony-netcdf-to-zarr
  arguments:
    parameters: # these will get filled in when the template is invoked
    - name: operation
      value: serialized operation
    - name: image
      value: harmony/netcdf-to-zarr:latest
    - name: image-pull-policy
      value: Always
    - name: AWS_DEFAULT_REGION
      value: us-west-2
    - name: USE_LOCALSTACK
      value: "false"
    - name: EDL_USERNAME
      value: username
    - name: EDL_PASSWORD
      value: password
    - name: STAGING_BUCKET
      value: bucket
    - name: TEXT_LOGGER
      value: logger
    - name: BACKEND_HOST
      value: "127.0.0.1"

  templates:
  - name: harmony-netcdf-to-zarr
    inputs:
      parameters:
      - name: operation
      - name: image
      - name: image-pull-policy
      - name: AWS_DEFAULT_REGION
      - name: USE_LOCALSTACK
      - name: EDL_USERNAME
      - name: EDL_PASSWORD
      - name: STAGING_BUCKET
      - name: TEXT_LOGGER
      - name: BACKEND_HOST
    container:
      # run netcdf-to-zar
      image: "{{inputs.parameters.image}}"
      imagePullPolicy: "{{inputs.parameters.image-pull-policy}}"
      command: ["python3"]
      args: ["-m", "harmony_netcdf_to_zarr", "--harmony-action", "invoke", "--harmony-input", "{{inputs.parameters.operation}}"]
      env:
        - name: AWS_DEFAULT_REGION
          value: "{{inputs.parameters.AWS_DEFAULT_REGION}}"
        - name: USE_LOCALSTACK
          value:  "{{inputs.parameters.USE_LOCALSTACK}}"
        - name: EDL_USERNAME
          value:  "{{inputs.parameters.EDL_USERNAME}}"
        - name: EDL_PASSWORD
          value:  "{{inputs.parameters.EDL_PASSWORD}}"
        - name: STAGING_BUCKET
          value:  "{{inputs.parameters.STAGING_BUCKET}}"
        - name: TEXT_LOGGER
          value:  "{{inputs.parameters.TEXT_LOGGER}}"
        - name: BACKEND_HOST
          value:  "{{inputs.parameters.BACKEND_HOST}}"