apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: podaac-netcdf-converter
spec:
  entrypoint: podaac-netcdf-converter
  templates:
    - name: podaac-netcdf-converter
      inputs:
        parameters:
          - name: operation
          - name: image
          - name: image-pull-policy
          - name: timeout
          - name: AWS_DEFAULT_REGION
          - name: USE_LOCALSTACK
          - name: STAGING_BUCKET
          - name: STAGING_PATH
          - name: TEXT_LOGGER
          - name: BACKEND_HOST
          - name: OAUTH_HOST
          - name: OAUTH_CLIENT_ID
          - name: OAUTH_REDIRECT_URI
          - name: FALLBACK_AUTHN_ENABLED
      podSpecPatch: '{"activeDeadlineSeconds":{{inputs.parameters.timeout}}}'
      container:
        image: "{{inputs.parameters.image}}"
        imagePullPolicy: "{{inputs.parameters.image-pull-policy}}"
        args:
          [
            "--harmony-action",
            "invoke",
            "--harmony-input",
            "{{inputs.parameters.operation}}",
          ]
        env:
          - name: AWS_DEFAULT_REGION
            value: "{{inputs.parameters.AWS_DEFAULT_REGION}}"
          - name: USE_LOCALSTACK
            value: "{{inputs.parameters.USE_LOCALSTACK}}"
          - name: OAUTH_UID
            valueFrom:
              secretKeyRef:
                name: argo-oauth-credentials
                key: username
          - name: OAUTH_PASSWORD
            valueFrom:
              secretKeyRef:
                name: argo-oauth-credentials
                key: password
          - name: SHARED_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: shared-secret
                key: secret-key
          - name: EDL_USERNAME
            valueFrom:
              secretKeyRef:
                name: argo-edl-credentials
                key: username
          - name: EDL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: argo-edl-credentials
                key: password
          - name: STAGING_BUCKET
            value: "{{inputs.parameters.STAGING_BUCKET}}"
          - name: STAGING_PATH
            value: "{{inputs.parameters.STAGING_PATH}}"
          - name: TEXT_LOGGER
            value: "{{inputs.parameters.TEXT_LOGGER}}"
          - name: BACKEND_HOST
            value: "{{inputs.parameters.BACKEND_HOST}}"
          - name: OAUTH_HOST
            value: "{{inputs.parameters.OAUTH_HOST}}"
          - name: OAUTH_CLIENT_ID
            value: "{{inputs.parameters.OAUTH_CLIENT_ID}}"
          - name: OAUTH_REDIRECT_URI
            value: "{{inputs.parameters.OAUTH_REDIRECT_URI}}"
          - name: FALLBACK_AUTHN_ENABLED
            value: "{{inputs.parameters.FALLBACK_AUTHN_ENABLED}}"
