apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: zpodaac-l2-subsetter-netcdf-to-zarr
spec:
  entrypoint: zpodaac-l2-subsetter-netcdf-to-zarr-steps
  templates:
    - name: zpodaac-l2-subsetter-netcdf-to-zarr-steps
      inputs:
        artifacts:
        - name: metadata
        parameters:
          - name: operation
          - name: stac-catalog-link
          - name: image-pull-policy
          - name: timeout
          - name: STAGING_PATH
      steps:
      - - name: podaac-l2-subsetter-step
          templateRef: 
            name: podaac-l2-subsetter
            template: podaac-l2-subsetter-service
          arguments:
            artifacts:
            - name: metadata
              from: "{{inputs.artifacts.metadata}}"
            parameters:
            - name: operation
              value: "{{inputs.parameters.operation}}"
            - name: stac-catalog-link
              value: "{{inputs.parameters.stac-catalog-link}}"
            - name: image-pull-policy
              value: "{{inputs.parameters.image-pull-policy}}"
            - name: timeout
              value: "{{inputs.parameters.timeout}}"
            - name: STAGING_PATH
              value: "{{inputs.parameters.STAGING_PATH}}"
      - - name: last-step
          templateRef: 
            name: harmony-netcdf-to-zarr
            template: harmony-netcdf-to-zarr-service
          arguments:
            artifacts:
            - name: metadata
              from: "{{steps.podaac-l2-subsetter-step.outputs.artifacts.metadata}}"
            parameters:
            - name: operation
              value: "{{inputs.parameters.operation}}"
            - name: stac-catalog-link
              value: "{{steps.podaac-l2-subsetter-step.outputs.parameters.stac-catalog-link}}"
            - name: image-pull-policy
              value: "{{inputs.parameters.image-pull-policy}}"
            - name: timeout
              value: "{{inputs.parameters.timeout}}"
            - name: STAGING_PATH
              value: "{{inputs.parameters.STAGING_PATH}}"
          # TODO we can't support a conditional here until https://github.com/argoproj/argo/issues/2496
          # is worked
          # when: "{{inputs.parameters.convert}} == true"
      outputs:
        artifacts:
          - name: metadata
            from: "{{steps.last-step.outputs.artifacts.metadata}}"
        parameters:
          - name: stac-catalog-link
            valueFrom:
              parameter: "{{steps.last-step.outputs.parameters.stac-catalog-link}}"