apiVersion: apps/v1
kind: Deployment
metadata:
  name: asf-gdal-service
  labels:
    name: asf-gdal-service
spec:
  replicas: 1
  selector:
    matchLabels:
      name: asf-gdal-service
  template:
    metadata:
      labels:
        name: asf-gdal-service
    spec:
      containers:
        - name: worker
          imagePullPolicy: $ASF_GDAL_SUBSETTER_IMAGE_PULL_POLICY
          image: $ASF_GDAL_SUBSETTER_IMAGE
          resources:
            limits:
              cpu: $ASF_GDAL_SUBSETTER_LIMITS_CPU
              memory: $ASF_GDAL_SUBSETTER_LIMITS_MEMORY
            requests:
              cpu: $ASF_GDAL_SUBSETTER_REQUESTS_CPU
              memory: $ASF_GDAL_SUBSETTER_REQUESTS_MEMORY
          envFrom:
          - configMapRef:
              name: harmony-env
          - secretRef:
              name: harmony-secrets
          volumeMounts:
            - mountPath: /tmp/metadata
              name: test-volume
          command: ["/bin/sh", "-c"]
          args:
            - while true; do
                date;
                sleep 10;
              done
        - name: manager
          imagePullPolicy: IfNotPresent
          image: $SERVICE_RUNNER_IMAGE
          resources:
            limits:
              cpu: $SERVICE_WRAPPER_LIMITS_CPU
              memory: $SERVICE_WRAPPER_LIMITS_MEMORY
            requests:
              cpu: $SERVICE_WRAPPER_REQUESTS_CPU
              memory: $SERVICE_WRAPPER_REQUESTS_MEMORY
          envFrom:
          - configMapRef:
              name: harmony-env
          - secretRef:
              name: harmony-secrets
          env:
          - name: BACKEND_HOST
            value: $BACKEND_HOST
          - name: BACKEND_PORT
            value: "$BACKEND_PORT"
          - name: HARMONY_SERVICE
            value: "$ASF_GDAL_SUBSETTER_IMAGE"
          - name: WORKING_DIR
            value: "/home"
          - name: INVOCATION_ARGS
            value: |-
              -m
              gdal_subsetter
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          ports:
            - containerPort: 5000
          volumeMounts:
            - mountPath: /tmp/metadata
              name: test-volume
      volumes:
      - name: test-volume
        hostPath:
          # directory location on host
          path: $HOST_VOLUME_PATH
          # this field is optional
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: asf-gdal-service
spec:
  ports:
    - name: frontend
      port: 5001
      targetPort: 5000
      protocol: TCP
  selector:
    name: asf-gdal-service
  type: LoadBalancer