apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-cmr
  labels:
    name: query-cmr
spec:
  replicas: 1
  selector:
    matchLabels:
      name: query-cmr
  template:
    metadata:
      labels:
        name: query-cmr
    spec:
      containers:
        - name: worker
          imagePullPolicy: IfNotPresent
          image: harmonyservices/query-cmr:latest
          envFrom:
          - configMapRef:
              name: harmony-env
          - secretRef:
              name: harmony-secrets
          volumeMounts:
            - mountPath: /tmp/metadata
              name: test-volume
          command: ["/bin/sh", "-c"]
          args:
            - while true; do
                date;
                sleep 10;
              done
        - name: manager
          imagePullPolicy: IfNotPresent
          image: harmonyservices/service-runner:latest
          envFrom:
          - configMapRef:
              name: harmony-env
          - secretRef:
              name: harmony-secrets
          env:
          - name: HARMONY_SERVICE
            value: "harmonyservices/query-cmr:latest"
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          ports:
            - containerPort: 5000
          volumeMounts:
            - mountPath: /tmp/metadata
              name: test-volume
      volumes:
      - name: test-volume
        hostPath:
          # directory location on host
          path: $HOST_VOLUME_PATH
          # this field is optional
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: query-cmr
spec:
  ports:
    - name: frontend
      port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    name: query-cmr
  type: LoadBalancer