apiVersion: apps/v1
kind: Deployment
metadata:
  name: harmony
  labels:
    name: harmony
spec:
  replicas: 1
  selector:
    matchLabels:
      name: harmony
  template:
    metadata:
      labels:
        name: harmony
    spec:
      containers:
        - name: harmony
          imagePullPolicy: IfNotPresent
          image: harmonyservices/harmony:latest
          command:
            - "/harmony/bin/start-harmony-in-container"
          env:
          # this is a bit confusing because HOST_VOLUME_PATH elsewhere refers to the path on the
          # node, not the container, but since we here we are running in a container we need to
          # set this to where the mount point is for the 'test-volume' below
          - name: HOST_VOLUME_PATH
            value: "/tmp/metadata"
          envFrom:
          - configMapRef:
              name: harmony-env
          - secretRef:
              name: harmony-secrets
          ports:
            - containerPort: 3000
            - containerPort: 3001
          volumeMounts:
            - mountPath: /tmp/metadata
              name: test-volume
      volumes:
      - name: test-volume
        hostPath:
          # directory location on host
          path: $HOST_VOLUME_PATH
          # this field is optional
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: harmony
spec:
  ports:
    - name: frontend
      port: 3000
      targetPort: 3000
      protocol: TCP
    - name: backend
      port: 3001
      targetPort: 3001
      protocol: TCP
  selector:
    name: harmony
  type: LoadBalancer