apiVersion: v1
kind: Pod
metadata:
  name: harmony-pod
  labels:
    name: harmony-pod
spec:
  containers:
        - name: harmony
          imagePullPolicy: IfNotPresent
          image: harmony:latest
          command:
            - "/harmony/bin/start-harmony"
          envFrom:
          - configMapRef:
              name: harmony-env
          volumeMounts:
              - mountPath: /harmony
                name: store
          ports:
            - containerPort: 3000
            - containerPort: 4001
  volumes:
    - name: store
      hostPath:
        path: /Users/jnorton1/Harmony/harmony
        type: Directory
      
---
apiVersion: v1
kind: Service
metadata:
  name: harmony
spec:
  ports:
    - name: frontend
      port: 3000
      targetPort: 3000
      protocol: TCP
    - name: backend
      port: 4001
      targetPort: 4001
      protocol: TCP
  selector:
    name: harmony-pod
  type: LoadBalancer