# Url to access prometheus
prometheus:
  url: http://prometheus.monitoring
  port: 9090

# Rules for custom metrics
rules:
  custom:
  - seriesQuery: 'num_ready_work_items'
    resources:
      overrides:
        name: {group: "apps", resource: "deployment"}
    name:
      matches: "num_ready_work_items"
      as: "num_ready_work_items"
    metricsQuery: '<<.Series>>{<<.LabelMatchers>>}'
