# Order for each CMR endpoint in this file will reflect precedence of the service when
# multiple services handle a collection

# Default argo configuration
x-argo-config: &default-argo-config
  name: argo
  params: &default-argo-params
    argo_url: !Env ${ARGO_URL}
    namespace: argo
    env: &default-argo-env
      USE_LOCALSTACK: !Env ${USE_LOCALSTACK}
      AWS_DEFAULT_REGION: us-west-2
      STAGING_BUCKET: !Env ${STAGING_BUCKET}
      TEXT_LOGGER: !Env ${TEXT_LOGGER}
      BACKEND_HOST: !Env ${BACKEND_HOST}
      EDL_USERNAME: !Env ${EDL_USERNAME}
      EDL_PASSWORD: !Env ${EDL_PASSWORD}
      OAUTH_UID: !Env ${OAUTH_UID}
      OAUTH_PASSWORD: !Env ${OAUTH_PASSWORD}
      OAUTH_HOST: !Env ${OAUTH_HOST}
      OAUTH_CLIENT_ID: !Env ${OAUTH_CLIENT_ID}
      OAUTH_REDIRECT_URI: !Env ${OAUTH_REDIRECT_URI}
      FALLBACK_AUTHN_ENABLED: !Env ${FALLBACK_AUTHN_ENABLED}

https://cmr.earthdata.nasa.gov:
  - name: asfdataservices/gdal-subsetter
    data_operation_version: '0.9.0'
    type:
      <<: *default-argo-config
      params:
        <<: *default-argo-params
        template: asf-gdal-subsetter
        image: !Env ${ASF_GDAL_IMAGE}
        image_pull_policy: !Env ${ASF_GDAL_IMAGE_PULL_POLICY}
        parallelism: !Env ${ASF_GDAL_PARALLELISM}
        env:
          <<: *default-argo-env
          STAGING_PATH: public/asfdataservices/gdal-subsetter
    collections:
      - C1595422627-ASF
      - C1214354031-ASF
      - C1808440897-ASF
    capabilities:
      subsetting:
        bbox: true
        variable: true
        multiple_variable: true
      output_formats:
        - image/tiff
        - image/png
        - image/gif
      reprojection: true

  - name: harmony/netcdf-to-zarr
    data_operation_version: '0.9.0'
    type:
      <<: *default-argo-config
      params:
        <<: *default-argo-params
        template: harmony-netcdf-to-zarr
        image: !Env ${NETCDF_TO_ZARR_IMAGE}
        image_pull_policy: !Env ${NETCDF_TO_ZARR_IMAGE_PULL_POLICY}
        parallelism: !Env ${NETCDF_TO_ZARR_PARALLELISM}
        env:
          <<: *default-argo-env
          STAGING_PATH: public/harmony/netcdf-to-zarr
    collections:
      - C1940468263-POCLOUD
      - C1938032626-POCLOUD
      - C1940473819-POCLOUD
      - C1940473819-POCLOUD
    maximum_sync_granules: 0
    capabilities:
      subsetting:
        variable: false
      output_formats:
        - application/x-zarr

  - name: harmony/gdal
    data_operation_version: '0.9.0'
    type:
      <<: *default-argo-config
      params:
        <<: *default-argo-params
        template: harmony-gdal
        image: !Env ${GDAL_IMAGE}
        image_pull_policy: !Env ${GDAL_IMAGE_PULL_POLICY}
        parallelism: !Env ${GDAL_PARALLELISM}
        env:
          <<: *default-argo-env
          STAGING_PATH: public/harmony/gdal
    collections:
      - C1756916832-XYZ_PROV
    capabilities:
      subsetting:
        bbox: true
        variable: true
        multiple_variable: true
      output_formats:
        - image/tiff
        - image/png
        - image/gif
      reprojection: true

  - name: podaac/l2-subsetter
    data_operation_version: '0.9.0'
    type:
      <<: *default-argo-config
      params:
        <<: *default-argo-params
        template: podaac-l2-subsetter
        image: !Env ${PODAAC_L2_SUBSETTER_IMAGE}
        image_pull_policy: !Env ${PODAAC_L2_SUBSETTER_IMAGE_PULL_POLICY}
        parallelism: !Env ${PODAAC_L2_SUBSETTER_PARALLELISM}
        env:
          <<: *default-argo-env
          STAGING_PATH: public/podaac/l2-subsetter
    collections:
      - C1940473819-POCLOUD
      - C1940475563-POCLOUD
      - C1940466008-POCLOUD
    capabilities:
      subsetting:
        bbox: true
        variable: true
      output_formats:
        - application/netcdf # Incorrect mime-type, remove when no longer needed
        - application/x-netcdf4

https://cmr.uat.earthdata.nasa.gov:

  - name: asfdataservices/gdal-subsetter
    data_operation_version: '0.9.0'
    type:
      <<: *default-argo-config
      params:
        <<: *default-argo-params
        template: asf-gdal-subsetter
        image: !Env ${ASF_GDAL_IMAGE}
        image_pull_policy: !Env ${ASF_GDAL_IMAGE_PULL_POLICY}
        parallelism: !Env ${ASF_GDAL_PARALLELISM}
        env:
          <<: *default-argo-env
          STAGING_PATH: public/asfdataservices/gdal-subsetter
    collections:
      - C1225776654-ASF
      - C1207038647-ASF
      - C1233629671-ASF
    capabilities:
      subsetting:
        bbox: true
        variable: true
        multiple_variable: true
      output_formats:
        - image/tiff
        - image/png
        - image/gif
      reprojection: true

  - name: harmony/gdal
    data_operation_version: '0.9.0'
    type:
      <<: *default-argo-config
      params:
        <<: *default-argo-params
        template: harmony-gdal
        image: !Env ${GDAL_IMAGE}
        image_pull_policy: !Env ${GDAL_IMAGE_PULL_POLICY}
        parallelism: !Env ${GDAL_PARALLELISM}
        env:
          <<: *default-argo-env
          STAGING_PATH: public/harmony/gdal
    collections:
      - C1233800302-EEDTEST
      - C1234088182-EEDTEST
    capabilities:
      subsetting:
        bbox: true
        variable: true
        multiple_variable: true
      output_formats:
        - image/tiff
        - image/png
        - image/gif
      reprojection: true

  - name: podaac/l2-subsetter
    data_operation_version: '0.9.0'
    type:
      <<: *default-argo-config
      params:
        <<: *default-argo-params
        template: podaac-l2-subsetter
        image: !Env ${PODAAC_L2_SUBSETTER_IMAGE}
        image_pull_policy: !Env ${PODAAC_L2_SUBSETTER_IMAGE_PULL_POLICY}
        parallelism: !Env ${PODAAC_L2_SUBSETTER_PARALLELISM}
        env:
          <<: *default-argo-env
          STAGING_PATH: public/podaac/l2-subsetter
    collections:
      - C1234208436-POCLOUD
      - C1234208437-POCLOUD
      - C1234208438-POCLOUD
      - C1234724470-POCLOUD
      - C1234724471-POCLOUD
      - C1234071416-POCLOUD
    capabilities:
      subsetting:
        bbox: true
        variable: true
      output_formats:
        - application/netcdf # Incorrect mime-type, remove when no longer needed
        - application/x-netcdf4

  - name: ds/swot-reproject
    data_operation_version: '0.9.0'
    batch_size: 1
    type:
      <<: *default-argo-config
      params:
        <<: *default-argo-params
        template: swot-reproject
        image: !Env ${SWOT_REPR_IMAGE}
        image_pull_policy: !Env ${SWOT_REPR_IMAGE_PULL_POLICY}
        parallelism: !Env ${SWOT_REPR_PARALLELISM}
        env:
          <<: *default-argo-env
          STAGING_PATH: public/sds/swot-reproject
    collections:
      - C1233860183-EEDTEST
      - C1233800302-EEDTEST
      - C1221286860-NSIDC_TS1
      - C1226288788-EDF_DEV07
      - C1233147317-EEDTEST
      - C1233147319-EEDTEST
      - C1234724470-POCLOUD
    capabilities:
      subsetting:
        bbox: false
        variable: false
      output_formats:
        - image/tiff
        - image/png
        - image/gif
        - application/netcdf # Incorrect mime-type, remove when no longer needed
        - application/x-netcdf4
      reprojection: true

  - name: sds/variable-subsetter
    data_operation_version: '0.9.0'
    type:
      <<: *default-argo-config
      params:
        <<: *default-argo-params
        template: var-subsetter
        image: !Env ${VAR_SUBSETTER_IMAGE}
        image_pull_policy: !Env ${VAR_SUBSETTER_IMAGE_PULL_POLICY}
        parallelism: !Env ${VAR_SUBSETTER_PARALLELISM}
        env:
          <<: *default-argo-env
          STAGING_PATH: public/sds/variable-subsetter
    data_url_pattern: 'opendap' # look for the string literal "opendap" in the data URL
    collections:
      - C1234714691-EEDTEST  # ATL03
      - C1234714698-EEDTEST  # ATL08
    capabilities:
      subsetting:
        variable: true
      output_formats:
        - application/netcdf # Incorrect mime-type, remove when no longer needed
        - application/x-netcdf4

  # This is an example service and backend from example/http-backend.js mounted by
  # the frontend callback server.
  # EOSS Example: curl -Lnbj 'http://localhost:3000/C1104-PVC_TS2/eoss/0.2.0/items/G1216319051-PVC_TS2'
  - name: harmony/example
    data_operation_version: '0.9.0'
    enabled: !Env ${EXAMPLE_SERVICES}
    type:
      name: http
      params:
        url: http://localhost:4000/example/harmony
    collections:
      # AMSR-E/Aqua L2B Global Swath Ocean Products derived from Wentz Algorithm V086
      # Good example, being in UAT, global, many public non-global granules,
      # and not yet on the services roadmap.
      - C1104-PVC_TS2
    capabilities:
      subsetting:
        variable: true
        bbox: true
      output_formats:
        - image/tiff
      reprojection: true

  # This is an example service and backend from example/http-backend.js mounted by
  # the frontend callback server.
  - name: harmony/chaining-example
    data_operation_version: '0.9.0'
    batch_size: 2000
    type:
      <<: *default-argo-config
      params:
        <<: *default-argo-params
        # Minimal parameters for current partial chaining implementation
        image: harmony/query-cmr:latest
        template_type: chaining
        env:
          <<: *default-argo-env
          LOCALSTACK_HOST: !Env ${BACKEND_HOST}
    collections:
      # AMSR-E/Aqua L2A Global Swath Spatially-Resampled Brightness Temperatures (Tb) V086
      # Good example, being in UAT, global, many public non-global granules,
      # and not yet on the services roadmap.
      - C1096-PVC_TS2
    capabilities:
      subsetting:
        variable: true
        bbox: true
      output_formats:
        - image/tiff
      reprojection: true

   # This is an example service using a result handler
  - name: harmony/result-handler-example
    data_operation_version: '0.9.0'
    batch_size: 2
    type:
      <<: *default-argo-config
      params:
        <<: *default-argo-params
        image: harmony/query-cmr:latest
        template: test-chain-with-result-handler
        image_pull_policy: !Env ${DEFAULT_IMAGE_PULL_POLICY}
        parallelism: !Env ${DEFAULT_PARALLELISM}
        env:
          <<: *default-argo-env
          STAGING_PATH: public/harmony/result-handler-example
    collections:
      # AMSR-E/Aqua L2A Global Swath Spatially-Resampled Brightness Temperatures (Tb) V086
      # Good example, being in UAT, global, many public non-global granules,
      # and not yet on the services roadmap.
      - C1096-PVC_TS2
    capabilities:
      subsetting:
        bbox: false
        variable: false
      output_formats:
        - image/tiff
        - image/png
        - image/gif
        - application/netcdf # Incorrect mime-type, remove when no longer needed
        - application/x-netcdf4
      reprojection: true

  # PO.DAAC Shapefiles
  - name: podaac/ps3
    data_operation_version: '0.9.0'
    type:
      <<: *default-argo-config
      params:
        <<: *default-argo-params
        template: podaac-ps3
        image: !Env ${PODAAC_PS3_IMAGE}
        image_pull_policy: !Env ${PODAAC_PS3_IMAGE_PULL_POLICY}
        parallelism: !Env ${PODAAC_PS3_PARALLELISM}
        env:
          <<: *default-argo-env
          STAGING_PATH: public/podaac/ps3
    collections:
      - C1234530532-EEDTEST
      - C1234530533-EEDTEST
    capabilities:
      subsetting:
        shape: true
        variable: false
      output_formats:
        - application/shapefile+zip

  # PO.DAAC NetCDF to COG
  - name: podaac/netcdf-converter
    data_operation_version: '0.9.0'
    type:
      <<: *default-argo-config
      params:
        <<: *default-argo-params
        template: podaac-netcdf-converter
        image: !Env ${PODAAC_NETCDF_CONVERTER_IMAGE}
        image_pull_policy: !Env ${PODAAC_NETCDF_CONVERTER_IMAGE_PULL_POLICY}
        parallelism: !Env ${PODAAC_NETCDF_CONVERTER_PARALLELISM}
        env:
          <<: *default-argo-env
          STAGING_PATH: public/podaac/netcdf-converter
    collections:
      - C1234410736-POCLOUD
    maximum_sync_granules: 0
    capabilities:
      subsetting:
        shape: false
        variable: false
      output_formats:
        - image/tiff

  - name: harmony/netcdf-to-zarr
    data_operation_version: '0.9.0'
    type:
      <<: *default-argo-config
      params:
        <<: *default-argo-params
        template: harmony-netcdf-to-zarr
        image: !Env ${NETCDF_TO_ZARR_IMAGE}
        image_pull_policy: !Env ${NETCDF_TO_ZARR_IMAGE_PULL_POLICY}
        parallelism: !Env ${NETCDF_TO_ZARR_PARALLELISM}
        env:
          <<: *default-argo-env
          STAGING_PATH: public/harmony/netcdf-to-zarr
    collections:
      - C1234088182-EEDTEST
      - C1233800302-EEDTEST
      - C1233860183-EEDTEST
      - C1234410736-POCLOUD
      - C1234082763-POCLOUD
      - C1234071416-POCLOUD
      - C1234208437-POCLOUD
      - C1234208436-POCLOUD
      - C1234208438-POCLOUD
      - C1234724470-POCLOUD
      - C1234724471-POCLOUD
    maximum_sync_granules: 0
    capabilities:
      subsetting:
        variable: false
      output_formats:
        - application/x-zarr
