# Order for each CMR endpoint in this file will reflect precedence of the service when
# multiple services handle a collection

# Default turbo configuration
x-turbo-config: &default-turbo-config
  name: turbo
  params: &default-turbo-params
    env: &default-turbo-env
      USE_LOCALSTACK: !Env ${USE_LOCALSTACK}
      LOCALSTACK_HOST: !Env ${BACKEND_HOST}
      AWS_DEFAULT_REGION: us-west-2
      STAGING_BUCKET: !Env ${STAGING_BUCKET}
      TEXT_LOGGER: !Env ${TEXT_LOGGER}
      BACKEND_HOST: !Env ${BACKEND_HOST}
      EDL_USERNAME: !Env ${EDL_USERNAME}
      EDL_PASSWORD: !Env ${EDL_PASSWORD}
      OAUTH_UID: !Env ${OAUTH_UID}
      OAUTH_PASSWORD: !Env ${OAUTH_PASSWORD}
      OAUTH_HOST: !Env ${OAUTH_HOST}
      OAUTH_CLIENT_ID: !Env ${OAUTH_CLIENT_ID}
      OAUTH_REDIRECT_URI: !Env ${OAUTH_REDIRECT_URI}
      FALLBACK_AUTHN_ENABLED: !Env ${FALLBACK_AUTHN_ENABLED}

https://cmr.uat.earthdata.nasa.gov:
  - name: harmony/sample-service
    data_operation_version: '0.17.0'
    type:
      <<: *default-turbo-config
      params:
        <<: *default-turbo-params
        env:
          <<: *default-turbo-env
          STAGING_PATH: public/harmony/sample-service
    collections:
      - id: C1234088182-EEDTEST
    capabilities:
      subsetting:
        bbox: true
        variable: true
        shape: true
      output_formats:
        - application/netcdf
        - application/netcdf4
    steps:
      - image: !Env ${QUERY_CMR_IMAGE}
      - image: !Env ${HARMONY_SAMPLE_SERVICE_IMAGE}
