# Order in this file will reflect precedence of the service when multiple services handle a collection until
# smarter service matching is implemented.

- name: harmony/gdal
  data_operation_version: '0.6.0'
  type:
    name: docker
    params:
      image: !Env ${GDAL_IMAGE}
      env:
        USE_LOCALSTACK: !Env ${USE_LOCALSTACK}
        AWS_DEFAULT_REGION: us-west-2
        EDL_USERNAME: !Env ${EDL_USERNAME}
        EDL_PASSWORD: !Env ${EDL_PASSWORD}
        EDL_ENDPOINT: !Env ${EDL_ENDPOINT}
        STAGING_BUCKET: !Env ${STAGING_BUCKET}
        STAGING_PATH: public/harmony/gdal
        TEXT_LOGGER: !Env ${TEXT_LOGGER}
  collections:
    - C1233800302-EEDTEST
    - C1234088182-EEDTEST
    - C1234410736-POCLOUD
    - C1234082763-POCLOUD
    - C1234071416-POCLOUD
  capabilities:
    subsetting:
      bbox: true
      variable: true
      multiple_variable: true
    output_formats:
      - image/tiff
      - image/png
      - image/gif
    projection_to_proj4: true

- name: sds/swot-reproject
  data_operation_version: '0.6.0'
  type:
    name: docker
    params:
      image: !Env ${SWOT_REPR_IMAGE}
      env:
        USE_LOCALSTACK: !Env ${USE_LOCALSTACK}
        AWS_DEFAULT_REGION: us-west-2
        EDL_USERNAME: !Env ${EDL_USERNAME}
        EDL_PASSWORD: !Env ${EDL_PASSWORD}
        EDL_ENDPOINT: !Env ${EDL_ENDPOINT}
        STAGING_BUCKET: !Env ${STAGING_BUCKET}
        STAGING_PATH: public/sds/swot-reproject
        TEXT_LOGGER: !Env ${TEXT_LOGGER}
  collections:
    - C1221286860-NSIDC_TS1
    - C1226288788-EDF_DEV07
    - C1233147317-EEDTEST
    - C1233147319-EEDTEST
    - C1233860183-EEDTEST
    - C1234410736-POCLOUD
    - C1234082763-POCLOUD
    - C1234071416-POCLOUD
  capabilities:
    subsetting:
      bbox: false
      variable: false
    output_formats:
      - image/tiff
      - image/png
      - image/gif
      - application/netcdf
    projection_to_proj4: true

# This is an example service and backend from example/http-backend.js mounted by
# the frontend callback server.
# EOSS Example: curl -Lnbj 'http://localhost:3000/C1104-PVC_TS2/eoss/0.2.0/items/G1216319051-PVC_TS2'
- name: harmony/example
  data_operation_version: '0.6.0'
  enabled: !Env ${EXAMPLE_SERVICES}
  type:
    name: http
    # Uncomment the following line to make the example service only return synchronous
    # results in order to test our sync -> async conversion.
    #synchronous_only: true
    params:
      url: http://localhost:3000/example/harmony
  collections:
    # AMSR-E/Aqua L2B Global Swath Ocean Products derived from Wentz Algorithm V086
    # Good example, being in UAT, global, many public non-global granules,
    # and not yet on the services roadmap.
    - C1104-PVC_TS2
  capabilities:
    subsetting:
      variable: true
    output_formats:
      - image/tiff

- name: podaac/http-service
  data_operation_version: '0.7.0'
  type:
    name: http
    synchronous_only: true
    params:
      url: https://d241qn3lj7he8d.cloudfront.net/dataOperation
  collections:
    - C1225996408-POCUMULUS
    - C1234530532-EEDTEST
    - C1234530533-EEDTEST
    - C1234208437-POCLOUD
    - C1234208436-POCLOUD
    - C1234208438-POCLOUD
  capabilities:
    subsetting:
      variable: true
    output_formats:
      - application/netcdf

- name: harmony/netcdf-to-zarr
  data_operation_version: '0.7.0'
  type:
    name: docker
    params:
      image: !Env ${NETCDF_TO_ZARR_IMAGE}
      env:
        USE_LOCALSTACK: !Env ${USE_LOCALSTACK}
        AWS_DEFAULT_REGION: us-west-2
        EDL_USERNAME: !Env ${EDL_USERNAME}
        EDL_PASSWORD: !Env ${EDL_PASSWORD}
        STAGING_BUCKET: !Env ${STAGING_BUCKET}
        STAGING_PATH: public/harmony/netcdf-to-zarr
        TEXT_LOGGER: !Env ${TEXT_LOGGER}
  collections:
    - C1233800302-EEDTEST
    - C1233860183-EEDTEST
    - C1234088182-EEDTEST
    - C1234410736-POCLOUD
    - C1234082763-POCLOUD
    - C1234071416-POCLOUD
    - C1234208437-POCLOUD
    - C1234208436-POCLOUD
    - C1234208438-POCLOUD
  maximum_sync_granules: 0
  capabilities:
    subsetting:
      variable: false
    output_formats:
      - application/x-zarr
