# Order for each CMR endpoint in this file will reflect precedence of the service when
# multiple services handle a collection

# Default argo configuration
x-argo-config: &default-argo-config
  name: argo
  params: &default-argo-params
    argo_url: !Env ${ARGO_URL}
    namespace: argo
    env: &default-argo-env
      USE_LOCALSTACK: !Env ${USE_LOCALSTACK}
      LOCALSTACK_HOST: !Env ${BACKEND_HOST}
      AWS_DEFAULT_REGION: us-west-2
      STAGING_BUCKET: !Env ${STAGING_BUCKET}
      TEXT_LOGGER: !Env ${TEXT_LOGGER}
      BACKEND_HOST: !Env ${BACKEND_HOST}
      EDL_USERNAME: !Env ${EDL_USERNAME}
      EDL_PASSWORD: !Env ${EDL_PASSWORD}
      OAUTH_UID: !Env ${OAUTH_UID}
      OAUTH_PASSWORD: !Env ${OAUTH_PASSWORD}
      OAUTH_HOST: !Env ${OAUTH_HOST}
      OAUTH_CLIENT_ID: !Env ${OAUTH_CLIENT_ID}
      OAUTH_REDIRECT_URI: !Env ${OAUTH_REDIRECT_URI}
      FALLBACK_AUTHN_ENABLED: !Env ${FALLBACK_AUTHN_ENABLED}

https://cmr.earthdata.nasa.gov:
  - name: asfdataservices/gdal-subsetter
    data_operation_version: '0.9.0'
    type:
      <<: *default-argo-config
      params:
        <<: *default-argo-params
        template: asf-gdal-subsetter
        template_type: chaining
        image: !Env ${ASF_GDAL_SUBSETTER_IMAGE}
        image_pull_policy: !Env ${ASF_GDAL_SUBSETTER_IMAGE_PULL_POLICY}
        parallelism: !Env ${ASF_GDAL_SUBSETTER_PARALLELISM}
        env:
          <<: *default-argo-env
          STAGING_PATH: public/asfdataservices/gdal-subsetter
    collections:
      - C1595422627-ASF
      - C1214354031-ASF
      - C1808440897-ASF
    capabilities:
      subsetting:
        shape: true
        bbox: true
        variable: true
        multiple_variable: true
      output_formats:
        - application/x-netcdf4
        - image/tiff
        - image/png
        - image/gif
      reprojection: true

  - name: harmony/netcdf-to-zarr
    data_operation_version: '0.9.0'
    type:
      <<: *default-argo-config
      params:
        <<: *default-argo-params
        template: harmony-netcdf-to-zarr
        template_type: chaining
        image: !Env ${HARMONY_NETCDF_TO_ZARR_IMAGE}
        image_pull_policy: !Env ${HARMONY_NETCDF_TO_ZARR_IMAGE_PULL_POLICY}
        parallelism: !Env ${HARMONY_NETCDF_TO_ZARR_PARALLELISM}
        env:
          <<: *default-argo-env
          STAGING_PATH: public/harmony/netcdf-to-zarr
    collections:
      - C1940468263-POCLOUD
      - C1938032626-POCLOUD
      - C1940473819-POCLOUD
      - C1940473819-POCLOUD
      - C1990404801-POCLOUD
      - C1990404814-POCLOUD
      - C1991543823-POCLOUD
      - C1991543805-POCLOUD
      - C1990404807-POCLOUD
      - C1990404805-POCLOUD
      - C1991543824-POCLOUD
      - C1991543745-POCLOUD
      - C1990404793-POCLOUD
      - C1990404798-POCLOUD
      - C1991543727-POCLOUD
      - C1991543735-POCLOUD
      - C1990404818-POCLOUD
      - C1990404792-POCLOUD
      - C1991543820-POCLOUD
      - C1991543803-POCLOUD
      - C1991543729-POCLOUD
      - C1991543819-POCLOUD
      - C1991543742-POCLOUD
      - C1990404788-POCLOUD
      - C1990404812-POCLOUD
      - C1991543712-POCLOUD
      - C1991543811-POCLOUD
      - C1990404810-POCLOUD
      - C1990404819-POCLOUD
      - C1991543734-POCLOUD
      - C1991543741-POCLOUD
      - C1990404797-POCLOUD
      - C1990404791-POCLOUD
      - C1991543737-POCLOUD
      - C1991543806-POCLOUD
      - C1991543804-POCLOUD
      - C1991543726-POCLOUD
      - C1991543702-POCLOUD
      - C1991543814-POCLOUD
      - C1991543752-POCLOUD
      - C1991543812-POCLOUD
      - C1991543740-POCLOUD
      - C1991543699-POCLOUD
      - C1991543739-POCLOUD
      - C1991543818-POCLOUD
      - C1991543733-POCLOUD
      - C1990404811-POCLOUD
      - C1990404823-POCLOUD
      - C1991543808-POCLOUD
      - C1991543732-POCLOUD
      - C1991543766-POCLOUD
      - C1990404815-POCLOUD
      - C1990404820-POCLOUD
      - C1991543763-POCLOUD
      - C1991543764-POCLOUD
      - C1991543821-POCLOUD
      - C1991543731-POCLOUD
      - C1991543724-POCLOUD
      - C1991543807-POCLOUD
      - C1991543730-POCLOUD
      - C1990404817-POCLOUD
      - C1990404790-POCLOUD
      - C1991543765-POCLOUD
      - C1991543700-POCLOUD
      - C1991543768-POCLOUD
      - C1990404813-POCLOUD
      - C1990404799-POCLOUD
      - C1991543744-POCLOUD
      - C1991543813-POCLOUD
      - C1991543817-POCLOUD
      - C1990404808-POCLOUD
      - C1990404796-POCLOUD
      - C1991543704-POCLOUD
      - C1991543760-POCLOUD
      - C1990404821-POCLOUD
      - C1990404795-POCLOUD
      - C1991543736-POCLOUD
      - C1991543728-POCLOUD
      - C1991543757-POCLOUD
    maximum_sync_granules: 0
    capabilities:
      subsetting:
        variable: false
      output_formats:
        - application/x-zarr

  - name: harmony/gdal
    data_operation_version: '0.10.0'
    type:
      <<: *default-argo-config
      params:
        <<: *default-argo-params
        template: harmony-gdal
        template_type: chaining
        image: !Env ${HARMONY_GDAL_IMAGE}
        image_pull_policy: !Env ${HARMONY_GDAL_IMAGE_PULL_POLICY}
        parallelism: !Env ${HARMONY_GDAL_PARALLELISM}
        env:
          <<: *default-argo-env
          STAGING_PATH: public/harmony/gdal
    collections:
      - C1756916832-XYZ_PROV
    capabilities:
      subsetting:
        bbox: true
        variable: true
        multiple_variable: true
      output_formats:
        - image/tiff
        - image/png
        - image/gif
      reprojection: true

  - name: podaac/l2-subsetter
    data_operation_version: '0.9.0'
    type:
      <<: *default-argo-config
      params:
        <<: *default-argo-params
        template: podaac-l2-subsetter
        template_type: chaining
        image: !Env ${PODAAC_L2_SUBSETTER_IMAGE}
        image_pull_policy: !Env ${PODAAC_L2_SUBSETTER_IMAGE_PULL_POLICY}
        parallelism: !Env ${PODAAC_L2_SUBSETTER_PARALLELISM}
        env:
          <<: *default-argo-env
          STAGING_PATH: public/podaac/l2-subsetter
    collections:
      - C1940473819-POCLOUD
      - C1940475563-POCLOUD
      - C1940466008-POCLOUD
      - C1968979997-POCLOUD
      - C1968979762-POCLOUD
    capabilities:
      subsetting:
        bbox: true
        variable: true
      output_formats:
        - application/netcdf # Incorrect mime-type, remove when no longer needed
        - application/x-netcdf4

https://cmr.uat.earthdata.nasa.gov:

  - name: asfdataservices/gdal-subsetter
    data_operation_version: '0.9.0'
    type:
      <<: *default-argo-config
      params:
        <<: *default-argo-params
        template: asf-gdal-subsetter
        template_type: chaining
        image: !Env ${ASF_GDAL_SUBSETTER_IMAGE}
        image_pull_policy: !Env ${ASF_GDAL_SUBSETTER_IMAGE_PULL_POLICY}
        parallelism: !Env ${ASF_GDAL_SUBSETTER_PARALLELISM}
        env:
          <<: *default-argo-env
          STAGING_PATH: public/asfdataservices/gdal-subsetter
    collections:
      - C1225776654-ASF
      - C1207038647-ASF
      - C1233629671-ASF
      - C1207181535-ASF
      - C1208013295-ASF
      - C1239927797-ASF
    capabilities:
      subsetting:
        shape: true
        bbox: true
        variable: true
        multiple_variable: true
      output_formats:
        - application/x-netcdf4
        - image/tiff
        - image/png
        - image/gif
      reprojection: true

  - name: harmony/gdal
    data_operation_version: '0.10.0'
    batch_size: 10
    type:
      <<: *default-argo-config
      params:
        <<: *default-argo-params
        template: harmony-gdal
        template_type: chaining
        image: !Env ${HARMONY_GDAL_IMAGE}
        image_pull_policy: !Env ${HARMONY_GDAL_IMAGE_PULL_POLICY}
        parallelism: !Env ${HARMONY_GDAL_PARALLELISM}
        env:
          <<: *default-argo-env
          STAGING_PATH: public/harmony/gdal
    collections:
      - C1233800302-EEDTEST
      - C1234088182-EEDTEST
    capabilities:
      subsetting:
        bbox: true
        variable: true
        multiple_variable: true
      output_formats:
        - image/tiff
        - image/png
        - image/gif
      reprojection: true

  - name: podaac/l2-subsetter
    data_operation_version: '0.9.0'
    type:
      <<: *default-argo-config
      params:
        <<: *default-argo-params
        template: podaac-l2-subsetter
        template_type: chaining
        image: !Env ${PODAAC_L2_SUBSETTER_IMAGE}
        image_pull_policy: !Env ${PODAAC_L2_SUBSETTER_IMAGE_PULL_POLICY}
        parallelism: !Env ${PODAAC_L2_SUBSETTER_PARALLELISM}
        env:
          <<: *default-argo-env
          STAGING_PATH: public/podaac/l2-subsetter
    collections:
      - C1234208436-POCLOUD
      - C1234208437-POCLOUD
      - C1234208438-POCLOUD
      - C1234724470-POCLOUD
      - C1234724471-POCLOUD
      - C1234071416-POCLOUD
      - C1238543220-POCLOUD
      - C1238543223-POCLOUD
      - C1238538240-POCLOUD
    capabilities:
      subsetting:
        bbox: true
        variable: true
      output_formats:
        - application/netcdf # Incorrect mime-type, remove when no longer needed
        - application/x-netcdf4

  - name: ds/swot-reproject
    data_operation_version: '0.9.0'
    batch_size: 1
    type:
      <<: *default-argo-config
      params:
        <<: *default-argo-params
        template: swot-reproject
        template_type: chaining
        image: !Env ${SWOT_REPROJECT_IMAGE}
        image_pull_policy: !Env ${SWOT_REPROJECT_IMAGE_PULL_POLICY}
        parallelism: !Env ${SWOT_REPROJECT_PARALLELISM}
        env:
          <<: *default-argo-env
          STAGING_PATH: public/sds/swot-reproject
    collections:
      - C1233860183-EEDTEST
      - C1233800302-EEDTEST
      - C1221286860-NSIDC_TS1
      - C1226288788-EDF_DEV07
      - C1233147317-EEDTEST
      - C1233147319-EEDTEST
      - C1234724470-POCLOUD
    capabilities:
      subsetting:
        bbox: false
        variable: false
      output_formats:
        - image/tiff
        - image/png
        - image/gif
        - application/netcdf # Incorrect mime-type, remove when no longer needed
        - application/x-netcdf4
      reprojection: true

  - name: sds/variable-subsetter
    data_operation_version: '0.9.0'
    type:
      <<: *default-argo-config
      params:
        <<: *default-argo-params
        template: var-subsetter
        image: !Env ${VAR_SUBSETTER_IMAGE}
        image_pull_policy: !Env ${VAR_SUBSETTER_IMAGE_PULL_POLICY}
        parallelism: !Env ${VAR_SUBSETTER_PARALLELISM}
        env:
          <<: *default-argo-env
          STAGING_PATH: public/sds/variable-subsetter
    data_url_pattern: 'opendap' # look for the string literal "opendap" in the data URL
    collections:
      - C1234714691-EEDTEST  # ATL03
      - C1234714698-EEDTEST  # ATL08
    capabilities:
      subsetting:
        variable: true
      output_formats:
        - application/netcdf # Incorrect mime-type, remove when no longer needed
        - application/x-netcdf4

  - name: sds/maskfill
    data_operation_version: '0.9.0'
    type:
      <<: *default-argo-config
      params:
        <<: *default-argo-params
        template: sds-maskfill
        template_type: chaining
        image: !Env ${SDS_MASKFILL_IMAGE}
        image_pull_policy: !Env ${SDS_MASKFILL_IMAGE_PULL_POLICY}
        parallelism: !Env ${SDS_MASKFILL_PARALLELISM}
        env:
          <<: *default-argo-env
          STAGING_PATH: public/sds/maskfill
    collections:
      - C1240150677-EEDTEST  # SPL4CMDL test collection
    capabilities:
      subsetting:
        shape: true

  # This is an example service and backend from example/http-backend.js mounted by
  # the frontend callback server.
  # EOSS Example: curl -Lnbj 'http://localhost:3000/C1104-PVC_TS2/eoss/0.2.0/items/G1216319051-PVC_TS2'
  - name: harmony/example
    data_operation_version: '0.10.0'
    enabled: !Env ${EXAMPLE_SERVICES}
    type:
      name: http
      params:
        url: http://localhost:4000/example/harmony
    collections:
      # AMSR-E/Aqua L2B Global Swath Ocean Products derived from Wentz Algorithm V086
      # Good example, being in UAT, global, many public non-global granules,
      # and not yet on the services roadmap.
      - C1104-PVC_TS2
    capabilities:
      subsetting:
        variable: true
        bbox: true
      output_formats:
        - image/tiff
      reprojection: true

  # This is an example service and backend from example/http-backend.js mounted by
  # the frontend callback server.
  - name: harmony/chaining-example
    data_operation_version: '0.9.0'
    batch_size: 2000
    type:
      name: argo
      params:
        # Minimal parameters for current partial chaining implementation
        image: harmony/query-cmr:latest
        template_type: chaining
        argo_url: !Env ${ARGO_URL}
        namespace: argo
        env:
          <<: *default-argo-env
          LOCALSTACK_HOST: !Env ${BACKEND_HOST}
    collections:
      # AMSR-E/Aqua L2A Global Swath Spatially-Resampled Brightness Temperatures (Tb) V086
      # Good example, being in UAT, global, many public non-global granules,
      # and not yet on the services roadmap.
      - C1096-PVC_TS2
    capabilities:
      subsetting:
        variable: true
        bbox: true
      output_formats:
        - image/tiff
      reprojection: true

  # PO.DAAC Shapefiles
  - name: podaac/ps3
    data_operation_version: '0.9.0'
    type:
      <<: *default-argo-config
      params:
        <<: *default-argo-params
        template: podaac-ps3
        image: !Env ${PODAAC_PS3_IMAGE}
        image_pull_policy: !Env ${PODAAC_PS3_IMAGE_PULL_POLICY}
        parallelism: !Env ${PODAAC_PS3_PARALLELISM}
        env:
          <<: *default-argo-env
          STAGING_PATH: public/podaac/ps3
    collections:
      - C1234530532-EEDTEST
      - C1234530533-EEDTEST
    capabilities:
      subsetting:
        shape: true
        variable: false
      output_formats:
        - application/shapefile+zip

  # PO.DAAC NetCDF to COG
  - name: podaac/netcdf-converter
    data_operation_version: '0.9.0'
    type:
      <<: *default-argo-config
      params:
        <<: *default-argo-params
        template: podaac-netcdf-converter
        image: !Env ${PODAAC_NETCDF_CONVERTER_IMAGE}
        image_pull_policy: !Env ${PODAAC_NETCDF_CONVERTER_IMAGE_PULL_POLICY}
        parallelism: !Env ${PODAAC_NETCDF_CONVERTER_PARALLELISM}
        env:
          <<: *default-argo-env
          STAGING_PATH: public/podaac/netcdf-converter
    collections:
      - C1234410736-POCLOUD
    maximum_sync_granules: 0
    capabilities:
      subsetting:
        shape: false
        variable: false
      output_formats:
        - image/tiff

  - name: harmony/netcdf-to-zarr
    data_operation_version: '0.10.0'
    type:
      <<: *default-argo-config
      params:
        <<: *default-argo-params
        template: harmony-netcdf-to-zarr
        template_type: chaining
        image: !Env ${HARMONY_NETCDF_TO_ZARR_IMAGE}
        image_pull_policy: !Env ${HARMONY_NETCDF_TO_ZARR_IMAGE_PULL_POLICY}
        parallelism: !Env ${HARMONY_NETCDF_TO_ZARR_PARALLELISM}
        env:
          <<: *default-argo-env
          STAGING_PATH: public/harmony/netcdf-to-zarr
    collections:
      - C1234088182-EEDTEST
      - C1233800302-EEDTEST
      - C1233860183-EEDTEST
      - C1234410736-POCLOUD
      - C1234082763-POCLOUD
      - C1234071416-POCLOUD
      - C1234208437-POCLOUD
      - C1234208436-POCLOUD
      - C1234208438-POCLOUD
      - C1234724470-POCLOUD
      - C1234724471-POCLOUD
      - C1239379704-POCLOUD
    maximum_sync_granules: 0
    capabilities:
      subsetting:
        variable: false
      output_formats:
        - application/x-zarr

  # CHAINED SERVICES BELOW HERE
  - name: harmony/podaac-l2-subsetter-netcdf-to-zarr
    data_operation_version: '0.9.0'
    type:
      <<: *default-argo-config
      params:
        <<: *default-argo-params
        template: podaac-l2-subsetter-netcdf-to-zarr
        template_type: chaining
        image: !Env ${HARMONY_NETCDF_TO_ZARR_IMAGE}
        image_pull_policy: !Env ${HARMONY_NETCDF_TO_ZARR_IMAGE_PULL_POLICY}
        parallelism: !Env ${HARMONY_NETCDF_TO_ZARR_PARALLELISM}
        env:
          <<: *default-argo-env
          STAGING_PATH: public/harmony/podaac-l2-subsetter-netcdf-to-zarr
    maximum_sync_granules: 0
    collections:
      - C1234208436-POCLOUD
      - C1234208437-POCLOUD
      - C1234208438-POCLOUD
      - C1234724470-POCLOUD
      - C1234724471-POCLOUD
      - C1234071416-POCLOUD
    capabilities:
      subsetting:
        bbox: true
        variable: true
      output_formats:
        - application/x-zarr

  - name: harmony/swot-repr-netcdf-to-zarr
    data_operation_version: '0.9.0'
    batch_size: 1
    type:
      <<: *default-argo-config
      params:
        <<: *default-argo-params
        template: swot-reproject-netcdf-to-zarr
        template_type: chaining
        image: !Env ${HARMONY_NETCDF_TO_ZARR_IMAGE}
        image_pull_policy: !Env ${HARMONY_NETCDF_TO_ZARR_IMAGE_PULL_POLICY}
        parallelism: !Env ${HARMONY_NETCDF_TO_ZARR_PARALLELISM}
        env:
          <<: *default-argo-env
          STAGING_PATH: public/harmony/swot-repr-netcdf-to-zarr
    collections:
      - C1233860183-EEDTEST
      - C1233800302-EEDTEST
      - C1234724470-POCLOUD
    maximum_sync_granules: 0
    capabilities:
      subsetting:
        bbox: false
        variable: false
      output_formats:
        - image/tiff
        - image/png
        - image/gif
        - application/netcdf # Incorrect mime-type, remove when no longer needed
        - application/x-netcdf4
        - application/x-zarr
      reprojection: true
