- name: podaac-cloud/l2-subsetter-service
  type:
    name: docker
    params:
      image: !Env ${PO_L2_IMAGE}
      env:
        USE_LOCALSTACK: !Env ${USE_LOCALSTACK}
        AWS_DEFAULT_REGION: us-east-1
        EDL_USERNAME: !Env ${EDL_USERNAME}
        EDL_PASSWORD: !Env ${EDL_PASSWORD}
        EDL_ENDPOINT: !Env ${EDL_ENDPOINT}
        STAGING_BUCKET: !Env ${STAGING_BUCKET}
        STAGING_PATH: podaac-cloud/l2-subsetter-service
  collections:
    - C1225996408-POCUMULUS
  capabilities:
    subsetting:
      bbox: true
      variable: false # Default
    output_formats:
      - application/x-netcdf4
    output_projections:
      - CRS:84

- name: harmony/gdal
  type:
    name: docker
    params:
      image: !Env ${GDAL_IMAGE}
      env:
        USE_LOCALSTACK: !Env ${USE_LOCALSTACK}
        AWS_DEFAULT_REGION: us-east-1
        EDL_USERNAME: !Env ${EDL_USERNAME}
        EDL_PASSWORD: !Env ${EDL_PASSWORD}
        EDL_ENDPOINT: !Env ${EDL_ENDPOINT}
        STAGING_BUCKET: !Env ${STAGING_BUCKET}
        STAGING_PATH: harmony/gdal
  collections:
    - C1215669046-GES_DISC
    - C1226288788-EDF_DEV07
  capabilities:
    subsetting:
      bbox: true
      variable: true # Default
      multiple_variable: true
    output_formats:
      - image/tiff
      - image/png
      - image/gif
    projection_to_proj4: true

- name: harmony/chained-swot-l2
  type:
    name: chain
    params:
      services:
        - name: podaac-cloud/l2-subsetter-service
          updates:
            spatial.bbox: null
        - name: harmony/gdal
  collections:
    - C1225996408-POCUMULUS

# This is an example service and backend from example/http-backend.js mounted by
# the frontend callback server.
# EOSS Example: curl -Lnbj 'http://localhost:3000/C1104-PVC_TS2/eoss/0.1.0/items/G1216319051-PVC_TS2'
- name: harmony/example
  enabled: !Env ${EXAMPLE_SERVICES}
  type:
    name: http
    params:
      url: http://localhost:3000/example/harmony
  collections:
    # AMSR-E/Aqua L2B Global Swath Ocean Products derived from Wentz Algorithm V086
    # Good example, being in UAT, global, many public non-global granules,
    # and not yet on the services roadmap.
    - C1104-PVC_TS2