reporter: mocha-multi
reporterOptions: 'spec=-,mocha-junit-reporter=-'
file: # Files that get loaded before suite execution.  Helpful when running a single file.
  - test/helpers/env.ts
#  - test/helpers/hooks.ts
extension:
  - ts
require:
  - ts-node/register
  - tsconfig-paths/register
# node-option:
#   - 'experimental-specifier-resolution=node'
#   - 'loader=ts-node/esm'
recursive: true
exit: true
timeout: 2000
