apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: podaac-l2-subsetter
spec:
  entrypoint: podaac-l2-subsetter
  templates:
    - name: podaac-l2-subsetter
      inputs:
        parameters:
          - name: operation
          - name: image
          - name: image-pull-policy
          - name: timeout
          - name: AWS_DEFAULT_REGION
          - name: USE_LOCALSTACK
          - name: STAGING_BUCKET
          - name: TEXT_LOGGER
          - name: BACKEND_HOST
      podSpecPatch: '{"activeDeadlineSeconds":{{inputs.parameters.timeout}}}'
      container:
        image: "{{inputs.parameters.image}}"
        imagePullPolicy: "{{inputs.parameters.image-pull-policy}}"
        args:
          [
            "--harmony-action",
            "invoke",
            "--harmony-input",
            "{{inputs.parameters.operation}}",
          ]
        envFrom:
          - configMapRef:
              name: harmony-env
          - secretRef:
              name: harmony-secrets