name: Publish to DockerHub

on:
  push:
    branches:
      - main
  release:
    types:
       - published

env:
  DOCKER_USER: bilts

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Log into registry
        run: echo "${{ secrets.DOCKERHUB }}" | docker login -u "${DOCKER_USER}" --password-stdin
      - name: Setup Node
        run: |
          npm install
      - name: Build and publish images
        run: |
          VERSION=test-publish-update
          

          # build and publish images for all services
          VERSION="${VERSION}" lerna run build
          VERSION="${VERSION}" lerna run publish

