name: Run Notebooks
on:
  push:
    branches: [ harmony-1040 ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: osgeo/gdal
    steps:
      - uses: actions/checkout@v3
      - name: Set up notebook environment
        run: apt-get update