name: Run Notebooks
on:
  push:
    branches: [ harmony-1040 ]
jobs:
  run-notebooks:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docs
    container:
      image: osgeo/gdal
    steps:
      - uses: actions/checkout@v3
      - uses: extractions/netrc@v1
        with:
          machine: uat.urs.earthdata.nasa.gov
          username: ${{ secrets.EDL_USER }}
          password: ${{ secrets.EDL_PASSWORD }}
      - run: apt-get update
      - run: apt-get -y install python3-pip
      - run: pip install jupyter
      - run: pip install rasterio OWSLib GDAL matplotlib netCDF4 numpy
      - run: pip install s3fs zarr
      - run: pip install papermill
      - run: pip install -r notebook_helpers/requirements.txt
      - run: papermill "Harmony API introduction.ipynb" out.ipynb
