name: Run Notebooks
on:
  push:
    branches: [ harmony-1040 ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: osgeo/gdal
    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)